language: groovy
jdk:
- openjdk8
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Jeff Scott Brown"
  - GIT_EMAIL="brownj@ociweb.com"
  - secure: eky/foiB6CVSrsk/FelPA//+XfiPc4sHSa4W1q2dkpOKj44hwpFxbmoSQVg9Z7f4gpvh6jCrPHeMjkcB9iuKbmPVuZMctt5qBlmcHWathYhbsmyah2cfJFrQIehUD7FNQy41bhcDbjXRDvOGejCwXBJa8jtdmRGEVXaAGNNfTJM=
  - secure: HKKPR42zo/AuGFCo7BkERKWsh0oUMKUleDP1KOR+ePf5jT/aliPM+EjrJJq3kP/kE5Z534SUwoX6ObRuET0bbBiz1CbqZ0dEBgPC6+sHaP0zmSo39DD5ONNN2OvUM4DXq6AR6/9JxjxyikBYtWSzSEGor+9vKZ24v+R/XYocxyc=
  - secure: ZLA3ZB2eSh+dEsByMbymvcBx7UeSmNbWmIx9mHnAp/yULq/1jhIIznnB1H07geboS5pkAjbYj1NdZQ8h5MqxmCwOaGefUkN1N5TTV5ZfmD/rlzNzTKThpT7LfqfgPyfYUVOQfz9gkVFZ4t2NZ6yqf97hzASuEOcAUicR5nCi1Cw=
  - secure: YjeQFp8EH2cDOF38uDc9Fp82f/i6jFEoNAcxmylhny9Md8p+rVTBFhiwHBJj6aFX1iStPbWaRdPzJ9Tggmb99W/kMCzV/sh1a2e7LIs6ekh7yPVojrZr7otyx/tKzZ8LZfQUKRNfdsuyHwLzHskwgJbcVber5ln9GtFK52Qxf8w=
  - secure: ZbaeuQ557fSEic31Q4Qbn/cAo/5I/BIExpAfLmH0FYLLw8hPNTZkFZ7AD5ZdHK73a023bKvkwj519pWIXp68AqAgw9mG8NQIaHScJmvdGMNdoBEodaM1r87wT3iJQ33AH7u+yiAO6HyG2eaO37aZaBFVzK2sET8Hf8d8Ftl2cgM=
  - secure: ZcK52XtVZwygxCmNXDDOfT9e0s98vvXe8InT+4tdW7UNbrgNYAwd5K+T3zLnCqJSsEisEYnWnFwxp9AXEJtgLVaA4wzHezXcEgGVsBaoNxknKftL3GvgE2u4q5ehpZ7VvSTr4j+IcH8pn1d360GaJVJi8ZMNqMERVOQEJ/JqGqI=
  - secure: mLJaymC8mXL6xz9azUyNtZLMtWYAT6o7LbyJuytgAME91KXciTA83WkJKxqTZQeT/QWCkLwbGnvUUJRB4q2+hCjJ8nSDUmt/s4IBGU3E2Xdyz1ByZaxDszApvkzsURl63xYvxkZA457QJaAgRhpJYmRKefBaQW1Cv0BRRNSgzm0=
  - secure: F+Nt8ZMSWB2f9o865whWMw+KmM2nZXxGqMVgVLM+yJ6avrIqePaIwubhcFh8xsGA9GSqVRH5K6bJfPgCqLO94kMZV68iYBmPClOpuytY7Nb0AFPQP3FNdppLOTr6RpK0PyRCJLfgniU9QjSyz31ydedmawx1eFaQbYt2IKx24fg=
  - secure: JAOS1ZFUMLCbQiLBcC8vlB3xqO0f0AWGU+CPh3s1IIb5AoByD7aC5KJEA4r1Y623LGB3mVjvcn09xUb+IEmlq6IbGfMllWwrbnb0AZvobSMBKss82KjZErpRSNTWENipk1D/k7DX9mUaMlS2PS/qEPCOLq8QD3ZlJdBrXELzyUg=
  - secure: Qx9/n92ljYSlLAsMhl9m0zpjxERyosIlgrkWheHy4XT4KdXZ4Jw1PflKrmncuW62SUSJPkbNdHBiauUl+ZDQvRh+c9YPiNYyUuMAkcfQuCUdsoKbQF9wVQ5xV8YHxtZMp72exBxYXDQ6Hf8lGz8XhpL6Q46KYneYG/R+55kH5M0=
